#!/bin/bash

gui=(
	google-chrome
	google-drive
	iterm2
	evernote
	github
	pycharm-ce
	vlc
)

term=(
	bash
	git
	bash-git-prompt
	vim
	tmux
	python
	python3
	gcc
	wget
	brew-cask
)

echo "Installing cask..."
brew tap caskroom/cask
echo "Installing terminal app..."
brew install ${term[@]}
echo "Installing gui apps..."
brew cask install ${gui[@]}
echo "Setup complete."
