# Change prefix for <C-b> to <C-a>
unbind C-b
set -g prefix C-a

# Improve colors
set -g default-terminal 'screen-256color'

# Allow for faster key repitition 
set -s escape-time 0

# Renumber windows sequentially after closing any of them
set -g renumber-windows on

# Remove administrative debris(session name, hostname, time) in status bar
set -g status-left ''
set -g status-right ''

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*
setw -g aggressive-resize on

set -g status-bg default # Transparent statusbar background
set -g status-fg '#aaaaaa' # Light-grey foreground
set -g history-limit 1000 # increase scrollback lines

set -g pane-border-fg '#aaaaaa'
set -g pane-active-border-fg default
